# Generated by Django 3.1.5 on 2021-01-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=30, verbose_name='métrica')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'objetivo',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='descripción')),
                ('value', models.FloatField(default=0, verbose_name='meta')),
                ('percentage', models.FloatField(default=0, verbose_name='porcentaje')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.objective', verbose_name='objetivo')),
            ],
            options={
                'verbose_name': 'meta',
            },
        ),
    ]
